[package]
name = "PcapRacer"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"            # 输出 CSV 文件
serde = { version = "1", features = ["derive"] }
rayon = "1.8"          # 并发加速
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0"
indicatif = "0.17"